apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-secret
data:
  credentials: |
    [zack]
    aws_access_key_id = AKIAVR7Z2FQ3OTTODLUD
    aws_secret_access_key = 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
