apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-feed
  name: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: zackolivier/udagram-api-feed:v1
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
          volumeMounts:
            - mountPath: "/root/.aws/"
              name: aws-secret
      volumes:
        - name: aws-secret
          configMap:
            name: aws-secret
      
